name = "LeetCode"
uuid = "177aac61-66e1-4cb4-9340-6393b6c3fb4c"
authors = ["Jun Tian <tianjun.cpp@gmail.com> and contributors"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
BenchmarkTools = "0.5"
DataStructures = "0.18"
JuliaFormatter = "0.10, 0.11, 0.12, 0.13"
julia = "1.3"

[extras]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JuliaFormatter", "LibGit2", "Test"]
