name = "LeetCode"
uuid = "177aac61-66e1-4cb4-9340-6393b6c3fb4c"
authors = ["Jun Tian <tianjun.cpp@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
